spring: 
 profiles: 
  active: "dev"
logging: 
 pattern: 
 console: '%d %-5level %logger : %msg%n'
 level: 
  org.springframework: INFO
  org.hibernate: DEBUG
server: 
 sessionTimeout: 60
 
 
---
spring: 
 profiles: dev
  
datasource: 
 driver-class-name: org.postgresql.Driver
 url: jdbc:postgresql://localhost:5432/organization_bc
 username: postgres
 password: postgres
 jpa: 
  hibernate: 
  ddl-auto: update
  show-sql: false
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  open-in-view: false
  generate-ddl: false
  
---
spring: 
 profiles: cloud

datasource: 
#driver-class-name: org.postgresql.Driver
#url: ${vcap.services.postgres-external.credentials.jdbcUrl}
# username: ${vcap.services.postgres-external.credentials.username}
# password: ${vcap.services.postgres-external.credentials.password}
#  jpa: 
#  hibernate: 
#  ddl-auto: update
#  show-sql: false
#  database: postgresql
#  database-platform: org.hibernate.dialect.PostgreSQLDialect
#  open-in-view: false
#  generate-ddl: false
  
