spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/organization_bc
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
logging:
  pattern:
    console: '%d %-5level %logger : %msg%n'
  level:
    org.springframework: INFO
    org.hibernate: DEBUG
server:
  port: 8190
  sessionTimeout: 30